version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # Template: basic
  - package-ecosystem: "npm"
    directory: "/template-basic"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # Template: canvas-2d-resizable
  - package-ecosystem: "npm"
    directory: "/template-canvas-2d-resizable"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # Template: node-basic
  - package-ecosystem: "npm"
    directory: "/template-node-basic"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
