/** ATTENTION: This file is autogenerated by AssemblyScript compiler, please do not edit manually. */
declare namespace __AdaptedExports {
  /** Exported memory */
  export const memory: WebAssembly.Memory;
  /**
   * index.as/init
   * @param maxFrameBufferWidth `u32`
   * @param maxFrameBufferHeight `u32`
   */
  export function init(maxFrameBufferWidth: number, maxFrameBufferHeight: number): void;
  /**
   * index.as/renderFrame
   * @param width `u32`
   * @param height `u32`
   */
  export function renderFrame(width: number, height: number): void;
  /**
   * index.as/switchMode
   */
  export function switchMode(): void;
}
/** Instantiates the compiled WebAssembly module with the given imports. */
export declare function instantiate(module: WebAssembly.Module, imports: {
  env: unknown,
}): Promise<typeof __AdaptedExports>;

/** Shape of the WASM module compiled from AssemblyScript */
export type WasmModule = typeof __AdaptedExports;